Properly handle muted and controls video attributes
DeuxHuitHuit/288-toolkit pull request #18
Opened 2024-10-30 14:31 UTC by f-elix

For some reason Svelte doesn't correctly handle those attributes (see https://github.com/sveltejs/svelte/issues/6536). I don't know how we didn't catch this earlier, but this PR works around the issue.

Closes https://github.com/DeuxHuitHuit/288-toolkit/issues/9

2024-10-30 14:35 UTC, nitriques requested changes

2024-11-28 16:38 UTC, nitriques commented
Cc @vsylvestre same as your bug right ?

2024-11-28 16:39 UTC, f-elix commented
By the way this is supposed to be fixed in Svelte 5

2025-01-29 21:28 UTC, nitriques approved these changes

2025-01-29 21:28 UTC, merged